In [47]:
import pandas as pd
import numpy as np
from datetime import datetime
import re

pd.set_option('display.max_columns', None)

In [4]:
# load csv
df = pd.read_csv('../tables/2016-17_skaters.csv')
df.head()

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,PS,EV,PP,SH,GW,EV.1,PP.1,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%
0,1,Spencer Abbott\abbotsp01,28,CHI,LW,1,0,0,0,0,0,0.0,0,0,0,0,0,0,0,1,0.0,9,8:34,0,0,0,0,NaN
1,2,Justin Abdelkader\abdelju01,29,DET,LW,64,7,14,21,-20,50,0.7,2,5,0,1,11,2,1,104,6.7,1066,16:40,27,144,5,12,29.4
2,3,Pontus Aberg\abergpo01,23,NSH,LW,15,1,1,2,-2,4,-0.1,1,0,0,0,1,0,0,12,8.3,185,12:20,2,9,1,0,100.0
3,4,Noel Acciari\acciano01,25,BOS,C,29,2,3,5,3,16,0.5,2,0,0,0,3,0,0,24,8.3,301,10:22,5,80,11,18,37.9
4,5,Kenny Agostino\agostke01,24,STL,LW,7,1,2,3,0,2,0.3,1,0,0,0,1,1,0,17,5.9,89,12:47,3,9,0,0,NaN

In [4]:
df_exp = df.copy()
df_exp = df_exp.rename(columns={'Tm':'Team', "Pos":"Position", "GP":"Games Played", 'G': 'Goals', 'A':'Assists', 'PS':'Point Share', "GW":"GWG", 'EV':"Even Strength Goals", "PP":"PPG", "SH":"SHG", "S":"Shots"})
df_exp.head()

,Rk,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,EV.1,PP.1,SH.1,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%
0,1,Spencer Abbott\abbotsp01,28,CHI,LW,1,0,0,0,0,0,0.0,0,0,0,0,0,0,0,1,0.0,9,8:34,0,0,0,0,NaN
1,2,Justin Abdelkader\abdelju01,29,DET,LW,64,7,14,21,-20,50,0.7,2,5,0,1,11,2,1,104,6.7,1066,16:40,27,144,5,12,29.4
2,3,Pontus Aberg\abergpo01,23,NSH,LW,15,1,1,2,-2,4,-0.1,1,0,0,0,1,0,0,12,8.3,185,12:20,2,9,1,0,100.0
3,4,Noel Acciari\acciano01,25,BOS,C,29,2,3,5,3,16,0.5,2,0,0,0,3,0,0,24,8.3,301,10:22,5,80,11,18,37.9
4,5,Kenny Agostino\agostke01,24,STL,LW,7,1,2,3,0,2,0.3,1,0,0,0,1,1,0,17,5.9,89,12:47,3,9,0,0,NaN

In [5]:
df_exp = df_exp.drop(columns=['Rk', 'PP.1', 'EV.1', 'SH.1', 'FOL'])
df_exp.head()

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FO%
0,Spencer Abbott\abbotsp01,28,CHI,LW,1,0,0,0,0,0,0.0,0,0,0,0,1,0.0,9,8:34,0,0,0,NaN
1,Justin Abdelkader\abdelju01,29,DET,LW,64,7,14,21,-20,50,0.7,2,5,0,1,104,6.7,1066,16:40,27,144,5,29.4
2,Pontus Aberg\abergpo01,23,NSH,LW,15,1,1,2,-2,4,-0.1,1,0,0,0,12,8.3,185,12:20,2,9,1,100.0
3,Noel Acciari\acciano01,25,BOS,C,29,2,3,5,3,16,0.5,2,0,0,0,24,8.3,301,10:22,5,80,11,37.9
4,Kenny Agostino\agostke01,24,STL,LW,7,1,2,3,0,2,0.3,1,0,0,0,17,5.9,89,12:47,3,9,0,NaN

In [6]:
df_exp['Season'] = pd.NaT
df_exp.head()

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FO%,Season
0,Spencer Abbott\abbotsp01,28,CHI,LW,1,0,0,0,0,0,0.0,0,0,0,0,1,0.0,9,8:34,0,0,0,NaN,NaT
1,Justin Abdelkader\abdelju01,29,DET,LW,64,7,14,21,-20,50,0.7,2,5,0,1,104,6.7,1066,16:40,27,144,5,29.4,NaT
2,Pontus Aberg\abergpo01,23,NSH,LW,15,1,1,2,-2,4,-0.1,1,0,0,0,12,8.3,185,12:20,2,9,1,100.0,NaT
3,Noel Acciari\acciano01,25,BOS,C,29,2,3,5,3,16,0.5,2,0,0,0,24,8.3,301,10:22,5,80,11,37.9,NaT
4,Kenny Agostino\agostke01,24,STL,LW,7,1,2,3,0,2,0.3,1,0,0,0,17,5.9,89,12:47,3,9,0,NaN,NaT

In [7]:
#df_exp = df_exp.replace({'Season':'NaT'}, '2016-17')
df_exp['Season'] = df_exp['Season'].fillna('2016-17')
df_exp

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FO%,Season
0,Spencer Abbott\abbotsp01,28,CHI,LW,1,0,0,0,0,0,0.0,0,0,0,0,1,0.0,9,8:34,0,0,0,NaN,2016-17
1,Justin Abdelkader\abdelju01,29,DET,LW,64,7,14,21,-20,50,0.7,2,5,0,1,104,6.7,1066,16:40,27,144,5,29.4,2016-17
2,Pontus Aberg\abergpo01,23,NSH,LW,15,1,1,2,-2,4,-0.1,1,0,0,0,12,8.3,185,12:20,2,9,1,100.0,2016-17
3,Noel Acciari\acciano01,25,BOS,C,29,2,3,5,3,16,0.5,2,0,0,0,24,8.3,301,10:22,5,80,11,37.9,2016-17
4,Kenny Agostino\agostke01,24,STL,LW,7,1,2,3,0,2,0.3,1,0,0,0,17,5.9,89,12:47,3,9,0,NaN,2016-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,Mika Zibanejad\zibanmi01,23,NYR,C,56,14,23,37,9,16,4.2,10,4,0,2,119,11.8,956,17:04,27,23,494,52.0,2016-17
884,Harry Zolnierczyk\zolniha01,29,NSH,LW,24,2,2,4,-2,10,0.2,2,0,0,0,19,10.5,213,8:52,11,25,8,42.1,2016-17
885,Mats Zuccarello\zuccama01,29,NYR,RW,80,15,44,59,15,26,6.0,10,5,0,3,189,7.9,1506,18:50,52,85,6,46.2,2016-17
886,Jason Zucker\zuckeja01,25,MIN,LW,79,22,25,47,34,30,6.7,21,1,0,3,172,12.8,1208,15:17,42,73,1,20.0,2016-17
887,Valentin Zykov\zykovva01,21,CAR,LW,2,1,0,1,1,0,0.2,1,0,0,0,3,33.3,13,6:15,0,0,0,NaN,2016-17

## Reformatting the Raw Tables

### 2016-17

In [48]:
# load csv
df = pd.read_csv('../tables/2016-17_skaters.csv')

In [65]:
# format table
df = df.rename(columns={'Tm':'Team', "Pos":"Position", "GP":"Games Played", 'G': 'Goals', 'A':'Assists', 'PS':'Point Share', "GW":"GWG", 'EV':"Even Strength Goals", "PP":"PPG", "SH":"SHG", "S":"Shots"})
df = df.drop(columns=['Rk', 'PP.1', 'EV.1', 'SH.1', 'FOL', 'FO%','ATOI','Point Share','Even Strength Goals','FOW'])
df['Season'] = pd.NaT
df['Season'] = df['Season'].fillna(0)
#df = df.rename(columns={'PTS':"PTS 0"})

# save table
df.to_csv('../tables/good_tables/2016-17_skaters_2.csv')

In [35]:
df

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS 0,+/-,PIM,PPG,SHG,GWG,Shots,S%,TOI,BLK,HIT,FOW,Season
0,Spencer Abbott\abbotsp01,28,CHI,LW,1,0,0,0,0,0,0,0,0,1,0.0,9,0,0,0,0
1,Justin Abdelkader\abdelju01,29,DET,LW,64,7,14,21,-20,50,5,0,1,104,6.7,1066,27,144,5,0
2,Pontus Aberg\abergpo01,23,NSH,LW,15,1,1,2,-2,4,0,0,0,12,8.3,185,2,9,1,0
3,Noel Acciari\acciano01,25,BOS,C,29,2,3,5,3,16,0,0,0,24,8.3,301,5,80,11,0
4,Kenny Agostino\agostke01,24,STL,LW,7,1,2,3,0,2,0,0,0,17,5.9,89,3,9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,Mika Zibanejad\zibanmi01,23,NYR,C,56,14,23,37,9,16,4,0,2,119,11.8,956,27,23,494,0
884,Harry Zolnierczyk\zolniha01,29,NSH,LW,24,2,2,4,-2,10,0,0,0,19,10.5,213,11,25,8,0
885,Mats Zuccarello\zuccama01,29,NYR,RW,80,15,44,59,15,26,5,0,3,189,7.9,1506,52,85,6,0
886,Jason Zucker\zuckeja01,25,MIN,LW,79,22,25,47,34,30,1,0,3,172,12.8,1208,42,73,1,0
887,Valentin Zykov\zykovva01,21,CAR,LW,2,1,0,1,1,0,0,0,0,3,33.3,13,0,0,0,0

### 2017-18

In [50]:
# load csv
df1 = pd.read_csv('../tables/2017-18_skaters.csv')

In [64]:
# format table
df1 = df1.rename(columns={'Tm':'Team', "Pos":"Position", "GP":"Games Played", 'G': 'Goals', 'A':'Assists', 'PS':'Point Share', "GW":"GWG", 'EV':"Even Strength Goals", "PP":"PPG", "SH":"SHG", "S":"Shots"})
df1 = df1.drop(columns=['Rk', 'PP.1', 'EV.1', 'SH.1', 'FOL', 'FO%','ATOI','Point Share','Even Strength Goals','FOW'])
df1['Season'] = pd.NaT
df1['Season'] = df1['Season'].fillna(1)
#df1 = df1.rename(columns={'PTS':"PTS 1"})

# save table
df1.to_csv('../tables/good_tables/2017-18_skaters_2.csv')

In [37]:
df1

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS 1,+/-,PIM,PPG,SHG,GWG,Shots,S%,TOI,BLK,HIT,FOW,Season
0,Justin Abdelkader\abdelju01,30,DET,LW,75,13,22,35,-11,78,4,0,0,110,11.8,1241,40.0,174,47.0,1
1,Pontus Aberg\abergpo01,24,TOT,LW,53,4,12,16,9,10,0,0,3,70,5.7,645,8.0,24,4.0,1
2,Noel Acciari\acciano01,26,BOS,C,60,10,1,11,-6,9,0,1,0,66,15.2,775,41.0,152,42.0,1
3,Kenny Agostino\agostke01,25,BOS,LW,5,0,1,1,-1,4,0,0,0,11,0.0,60,1.0,4,0.0,1
4,Sebastian Aho\ahose01,20,CAR,RW,78,29,36,65,4,24,8,0,4,200,14.5,1398,17.0,65,78.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,Henrik Zetterberg\zettehe01,37,DET,LW,82,11,45,56,1,14,1,0,2,180,6.1,1599,34.0,49,666.0,1
886,Mika Zibanejad\zibanmi01,24,NYR,C,72,27,20,47,-23,14,14,0,4,212,12.7,1293,64.0,92,654.0,1
887,Mats Zuccarello\zuccama01,30,NYR,LW,80,16,37,53,-10,36,1,0,3,178,9.0,1514,67.0,62,21.0,1
888,Jason Zucker\zuckeja01,26,MIN,LW,82,33,31,64,8,44,7,1,7,222,14.9,1391,47.0,80,4.0,1
889,Valentin Zykov\zykovva01,22,CAR,LW,10,3,4,7,4,2,0,0,1,18,16.7,137,1.0,3,0.0,1

### 2018-19

In [52]:
# load csv
df2 = pd.read_csv('../tables/2018-19_skaters.csv')

In [63]:
# format table
df2 = df2.rename(columns={'Tm':'Team', "Pos":"Position", "GP":"Games Played", 'G': 'Goals', 'A':'Assists', 'PS':'Point Share', "GW":"GWG", 'EV':"Even Strength Goals", "PP":"PPG", "SH":"SHG", "S":"Shots"})
df2 = df2.drop(columns=['Rk', 'PP.1', 'EV.1', 'SH.1', 'FOL', 'FO%','ATOI','Point Share','Even Strength Goals','FOW'])
df2['Season'] = pd.NaT
df2['Season'] = df2['Season'].fillna(2)
#df2 = df2.rename(columns={'PTS':"PTS 2"})

# save table
df2.to_csv('../tables/good_tables/2018-19_skaters_2.csv')

In [41]:
df2

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS 2,+/-,PIM,PPG,SHG,GWG,Shots,S%,TOI,BLK,HIT,FOW,Season
0,Justin Abdelkader\abdelju01,31,DET,LW,71,6,13,19,-14,38,1,1,0,95,6.3,1093,34,185,52,2
1,Pontus Aberg\abergpo01,25,TOT,LW,59,12,13,25,-14,20,3,0,1,101,11.9,861,11,45,2,2
2,Vitaly Abramov\abramvi01,20,OTT,RW,1,0,0,0,-3,0,0,0,0,0,NaN,14,1,0,0,2
3,Noel Acciari\acciano01,27,BOS,C,72,6,8,14,-3,47,0,0,2,99,6.1,935,36,221,200,2
4,Kenny Agostino\agostke01,26,TOT,LW,63,6,18,24,-3,34,0,0,0,79,7.6,814,14,143,15,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,Jakub Zboril\zborija01,21,BOS,D,2,0,0,0,0,0,0,0,0,1,0.0,22,0,3,0,2
902,Mika Zibanejad\zibanmi01,25,NYR,C,82,30,44,74,-12,47,11,2,5,236,12.7,1686,66,134,830,2
903,Mats Zuccarello\zuccama01,31,TOT,LW,48,12,28,40,-8,24,3,0,1,104,11.5,953,43,57,10,2
904,Jason Zucker\zuckeja01,27,MIN,LW,81,21,21,42,-9,28,7,0,5,214,9.8,1383,38,87,2,2
905,Valentin Zykov\zykovva01,23,TOT,LW,28,2,3,5,-5,2,0,0,0,29,6.9,279,6,26,2,2

### 2019-20
(covid year 1)

In [54]:
# load csv
df3 = pd.read_csv('../tables/2019-20_skaters.csv')

In [62]:
# format table
df3 = df3.rename(columns={'Tm':'Team', "Pos":"Position", "GP":"Games Played", 'G': 'Goals', 'A':'Assists', 'PS':'Point Share', "GW":"GWG", 'EV':"Even Strength Goals", "PP":"PPG", "SH":"SHG", "S":"Shots"})
df3 = df3.drop(columns=['Rk', 'PP.1', 'EV.1', 'SH.1', 'FOL', 'FO%','ATOI','Point Share','Even Strength Goals','FOW'])
df3['Season'] = pd.NaT
df3['Season'] = df3['Season'].fillna(3)
#df3 = df3.rename(columns={'PTS':"PTS 3"})

# save table
df3.to_csv('../tables/good_tables/2019-20_skaters_2.csv')

In [40]:
df3

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS 3,+/-,PIM,PPG,SHG,GWG,Shots,S%,TOI,BLK,HIT,FOW,Season
0,Justin Abdelkader\abdelju01,32,DET,LW,49,0,3,3,-14,25,0,0,0,40,0.0,565,26,103,38,3
1,Pontus Aberg\abergpo01,26,TOR,LW,5,0,1,1,0,0,0,0,0,4,0.0,44,1,1,0,3
2,Vitaly Abramov\abramvi01,21,OTT,RW,2,1,0,1,0,2,0,0,0,3,33.3,12,0,0,0,3
3,Noel Acciari\acciano01,28,FLA,C,66,20,7,27,2,21,0,1,5,108,18.5,1054,103,121,381,3
4,Andrew Agozzino\agozzan01,29,TOT,LW,22,1,2,3,3,4,0,0,0,10,10.0,162,7,25,38,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,Travis Zajac\zajactr01,34,NJD,C,69,9,16,25,-12,28,1,1,1,72,12.5,1180,39,58,576,3
879,Mika Zibanejad\zibanmi01,26,NYR,C,57,41,34,75,9,14,15,3,6,208,19.7,1233,49,51,592,3
880,Mats Zuccarello\zuccama01,32,MIN,LW,65,15,22,37,-9,18,3,0,2,96,15.6,1036,36,13,9,3
881,Jason Zucker\zuckeja01,28,TOT,LW,60,20,21,41,-4,21,7,0,4,111,18.0,980,23,53,12,3
882,Valentin Zykov\zykovva01,24,VEG,LW,15,1,3,4,-2,6,1,0,0,19,5.3,183,3,20,0,3

### 2020-21
(covid year 2, each team played 56 games)

In [56]:
# load csv
df4 = pd.read_csv('../tables/2020-21_skaters.csv')

In [61]:
# format table
df4 = df4.rename(columns={'Tm':'Team', "Pos":"Position", "GP":"Games Played", 'G': 'Goals', 'A':'Assists', 'PS':'Point Share', "GW":"GWG", 'EV':"Even Strength Goals", "PP":"PPG", "SH":"SHG", "S":"Shots"})
df4 = df4.drop(columns=['Rk', 'PP.1', 'EV.1', 'SH.1', 'FOL', 'FO%','ATOI','Point Share','Even Strength Goals','FOW'])
df4['Season'] = pd.NaT
df4['Season'] = df4['Season'].fillna(4)
#df4 = df4.rename(columns={'PTS':"PTS 4"})

# save table
df4.to_csv('../tables/good_tables/2020-21_skaters_2.csv')

In [43]:
df4

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS 4,+/-,PIM,PPG,SHG,GWG,Shots,S%,TOI,BLK,HIT,FOW,Season
0,Vitaly Abramov\abramvi01,22,OTT,RW,2,0,0,0,0,0,0,0,0,0,NaN,19,0,0,0,4
1,Noel Acciari\acciano01,29,FLA,C,41,4,7,11,0,9,1,0,1,68,5.9,631,63,91,272,4
2,Calen Addison\addisca01,20,MIN,D,3,0,0,0,0,0,0,0,0,4,0.0,56,1,2,0,4
3,Kenny Agostino\agostke01,28,TOR,LW,1,0,0,0,0,0,0,0,0,0,NaN,4,0,0,0,4
4,Andrew Agozzino\agozzan01,30,ANA,LW,3,0,1,1,0,0,0,0,0,3,0.0,37,7,6,16,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
908,Mika Zibanejad\zibanmi01,27,NYR,C,56,24,26,50,2,18,10,2,7,171,14.0,1126,44,75,479,4
909,Radim Zohorna\zohorra01,24,PIT,F,8,2,2,4,4,4,0,0,1,8,25.0,72,0,7,5,4
910,Artem Zub\zubar01,25,OTT,D,47,3,11,14,4,26,0,0,1,39,7.7,864,70,89,0,4
911,Mats Zuccarello\zuccama01,33,MIN,LW,42,11,24,35,9,8,3,0,0,74,14.9,701,19,12,11,4
912,Jason Zucker\zuckeja01,29,PIT,LW,38,9,9,18,-8,21,1,0,1,67,13.4,596,15,69,3,4

### 2021-22
Test set

In [58]:
# load csv
test = pd.read_csv('../tables/2021-22_skaters.csv')

In [60]:
# format table
test = test.rename(columns={'Tm':'Team', "Pos":"Position", "GP":"Games Played", 'G': 'Goals', 'A':'Assists', 'PS':'Point Share', "GW":"GWG", 'EV':"Even Strength Goals", "PP":"PPG", "SH":"SHG", "S":"Shots"})
test = test.drop(columns=['Rk', 'PP.1', 'EV.1', 'SH.1', 'FOL', 'FO%','ATOI','Point Share','Even Strength Goals'])
test['Season'] = pd.NaT
test['Season'] = test['Season'].fillna(5)
#test = test.rename(columns={'PTS':"PTS test"})

# save table
test.to_csv('../tables/good_tables/2021-22_skaters_2.csv')

KeyError: "['Rk', 'PP.1', 'EV.1', 'SH.1', 'FOL', 'FO%', 'ATOI', 'Point Share', 'Even Strength Goals'] not found in axis"

In [46]:
test

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS test,+/-,PIM,PPG,SHG,GWG,Shots,S%,TOI,BLK,HIT,FOW,Season
0,Nicholas Abruzzese\abruzni01,22,TOR,C,9,1,0,1,-1,2,0,0,1,8,12.5,92,3,7,2,5
1,Noel Acciari\acciano01,30,FLA,C,20,3,5,8,2,11,0,0,1,32,9.4,240,16,48,84,5
2,Calen Addison\addisca01,21,MIN,D,15,2,2,4,-4,2,0,0,0,17,11.8,207,6,12,0,5
3,Andrew Agozzino\agozzan01,31,OTT,LW,1,0,0,0,0,0,0,0,0,1,0.0,7,0,4,1,5
4,Jack Ahcan\ahcanja01,24,BOS,D,6,1,0,1,-3,0,1,0,0,5,20.0,96,5,8,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,Mika Zibanejad\zibanmi01,28,NYR,C,81,29,52,81,30,12,15,1,3,219,13.2,1591,47,67,700,5
1000,Radim Zohorna\zohorra01,25,PIT,F,17,2,4,6,12,4,0,0,0,9,22.2,176,3,23,4,5
1001,Artem Zub\zubar01,26,OTT,D,81,6,16,22,1,60,0,0,0,92,6.5,1704,124,155,0,5
1002,Mats Zuccarello\zuccama01,34,MIN,LW,70,24,55,79,21,24,7,0,2,159,15.1,1301,33,36,21,5
1003,Jason Zucker\zuckeja01,30,PIT,LW,41,8,9,17,-2,15,2,0,0,102,7.8,608,20,66,4,5

## (the)

In [8]:
train1 = df
train1.head(1)

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,PS,EV,PP,SH,GW,EV.1,PP.1,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%
0,1,Spencer Abbott\abbotsp01,28,CHI,LW,1,0,0,0,0,0,0.0,0,0,0,0,0,0,0,1,0.0,9,8:34,0,0,0,0,NaN

In [126]:
train2 = df1
train2.head(1)

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FO%,Season
0,Justin Abdelkader\abdelju01,30,DET,LW,75,13,22,35,-11,78,2.5,9,4,0,0,110,11.8,1241,16:33,40.0,174,47.0,48.5,2017-18

In [127]:
train3 = df2
train3.head(1)

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FO%,Season
0,Justin Abdelkader\abdelju01,31,DET,LW,71,6,13,19,-14,38,0.1,4,1,1,0,95,6.3,1093,15:24,34,185,52,50.5,2018-19

In [128]:
train4 = df3
train4.head(1)

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FO%,Season
0,Justin Abdelkader\abdelju01,32,DET,LW,49,0,3,3,-14,25,-0.9,0,0,0,0,40,0.0,565,11:32,26,103,38,55.1,2019-20

In [129]:
train5 = df4
train5.head(1)

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FO%,Season
0,Vitaly Abramov\abramvi01,22,OTT,RW,2,0,0,0,0,0,0.0,0,0,0,0,0,NaN,19,9:43,0,0,0,NaN,2020-21

In [122]:
test.head(3)

,Player,Age,Team,Position,Games Played,Goals,Assists,PTS,+/-,PIM,Point Share,Even Strength Goals,PPG,SHG,GWG,Shots,S%,TOI,ATOI,BLK,HIT,FOW,FO%,Season
0,Nicholas Abruzzese\abruzni01,22,TOR,C,9,1,0,1,-1,2,0.0,1,0,0,1,8,12.5,92,10:13,3,7,2,28.6,2021-22
1,Noel Acciari\acciano01,30,FLA,C,20,3,5,8,2,11,0.6,3,0,0,1,32,9.4,240,11:59,16,48,84,50.6,2021-22
2,Calen Addison\addisca01,21,MIN,D,15,2,2,4,-4,2,0.3,2,0,0,0,17,11.8,207,13:47,6,12,0,NaN,2021-22

## (in the) (on the)

In [14]:
train1['ATOI'][0]

'8:34'

In [19]:
datetime_object = datetime.strptime(train1['ATOI'][0], '%M:%S')

In [22]:
print(datetime_object)

1900-01-01 00:08:34

In [28]:
datetime_object

datetime.datetime(1900, 1, 1, 0, 8, 34)

In [30]:
train1['ATOI']

0       8:34
1      16:40
2      12:20
3      10:22
4      12:47
       ...
883    17:04
884     8:52
885    18:50
886    15:17
887     6:15
Name: ATOI, Length: 888, dtype: object

In [27]:
train1[train1['Player'] == 'Auston Matthews\matthau01']

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,PS,EV,PP,SH,GW,EV.1,PP.1,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%
499,500,Auston Matthews\matthau01,19,TOR,C,82,40,29,69,2,14,9.7,32,8,0,8,16,13,0,279,14.3,1446,17:38,61,21,530,600,46.9

In [59]:
def avg_toi(df):
    df['Avg TOI'] = round(df['TOI']/df['GP'], 3)
    return df

def points_per_60(df):
    df['Pts per 60'] = round(df['PTS']/df['Avg TOI'], 3)
    return df

def points_per_game(df):
    df['Pts per Game'] = round(df['PTS']/df['GP'], 3)
    return df

def pp60(df):
    df['P/60'] = round(df["PTS"] * 60 / df['Avg TOI'], 3)
    return df

def p_per60(df): # THIS ONE 
    df['PP60'] = round(df["PTS"] * 60 / df['TOI'], 3)
    return df

In [60]:
p_per60(df)

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,PS,EV,PP,SH,GW,EV.1,PP.1,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%,Avg TOI,Pts per 60,Pts per Game,P/60,PP60
0,1,Spencer Abbott\abbotsp01,28,CHI,LW,1,0,0,0,0,0,0.0,0,0,0,0,0,0,0,1,0.0,9,8:34,0,0,0,0,NaN,9.000000,0.000000,0.000,0.000,0.000
1,2,Justin Abdelkader\abdelju01,29,DET,LW,64,7,14,21,-20,50,0.7,2,5,0,1,11,2,1,104,6.7,1066,16:40,27,144,5,12,29.4,16.656250,1.260788,0.328,75.647,1.182
2,3,Pontus Aberg\abergpo01,23,NSH,LW,15,1,1,2,-2,4,-0.1,1,0,0,0,1,0,0,12,8.3,185,12:20,2,9,1,0,100.0,12.333333,0.162162,0.133,9.730,0.649
3,4,Noel Acciari\acciano01,25,BOS,C,29,2,3,5,3,16,0.5,2,0,0,0,3,0,0,24,8.3,301,10:22,5,80,11,18,37.9,10.379310,0.481728,0.172,28.904,0.997
4,5,Kenny Agostino\agostke01,24,STL,LW,7,1,2,3,0,2,0.3,1,0,0,0,1,1,0,17,5.9,89,12:47,3,9,0,0,NaN,12.714286,0.235955,0.429,14.157,2.022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,Mika Zibanejad\zibanmi01,23,NYR,C,56,14,23,37,9,16,4.2,10,4,0,2,16,7,0,119,11.8,956,17:04,27,23,494,456,52.0,17.071429,2.167364,0.661,130.042,2.322
884,885,Harry Zolnierczyk\zolniha01,29,NSH,LW,24,2,2,4,-2,10,0.2,2,0,0,0,2,0,0,19,10.5,213,8:52,11,25,8,11,42.1,8.875000,0.450704,0.167,27.042,1.127
885,886,Mats Zuccarello\zuccama01,29,NYR,RW,80,15,44,59,15,26,6.0,10,5,0,3,35,9,0,189,7.9,1506,18:50,52,85,6,7,46.2,18.825000,3.134130,0.738,188.048,2.351
886,887,Jason Zucker\zuckeja01,25,MIN,LW,79,22,25,47,34,30,6.7,21,1,0,3,25,0,0,172,12.8,1208,15:17,42,73,1,4,20.0,15.291139,3.073675,0.595,184.421,2.334
887,888,Valentin Zykov\zykovva01,21,CAR,LW,2,1,0,1,1,0,0.2,1,0,0,0,0,0,0,3,33.3,13,6:15,0,0,0,0,NaN,6.500000,0.153846,0.500,9.231,4.615

points_per_60(df)

In [64]:
df[df['Player'] == 'Auston Matthews\matthau01']

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,PS,EV,PP,SH,GW,EV.1,PP.1,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%,Avg TOI,Pts per 60,Pts per Game,P/60,PP60
499,500,Auston Matthews\matthau01,19,TOR,C,82,40,29,69,2,14,9.7,32,8,0,8,16,13,0,279,14.3,1446,17:38,61,21,530,600,46.9,17.634146,3.912863,0.841,234.772,2.863

In [63]:
df[df['Player'] == 'Connor McDavid\mcdavco01']

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,PS,EV,PP,SH,GW,EV.1,PP.1,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%,Avg TOI,Pts per 60,Pts per Game,P/60,PP60
509,510,Connor McDavid\mcdavco01,20,EDM,C,82,30,70,100,27,26,12.8,26,3,1,6,45,24,1,251,12.0,1733,21:08,29,34,348,458,43.2,21.134146,4.731679,1.22,283.901,3.462

In [62]:
df[df['Player'] == 'Evgeni Malkin\malkiev01']

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,PS,EV,PP,SH,GW,EV.1,PP.1,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%,Avg TOI,Pts per 60,Pts per Game,P/60,PP60
480,481,Evgeni Malkin\malkiev01,30,PIT,C,62,33,39,72,18,77,9.9,22,11,0,6,27,12,0,191,17.3,1154,18:37,25,40,365,481,43.1,18.612903,3.868284,1.161,232.097,3.744

In [61]:
df[df['Player'] == 'Sidney Crosby\crosbsi01']

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,PS,EV,PP,SH,GW,EV.1,PP.1,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%,Avg TOI,Pts per 60,Pts per Game,P/60,PP60
149,150,Sidney Crosby\crosbsi01,29,PIT,C,75,44,45,89,17,24,12.3,30,14,0,5,34,11,0,255,17.3,1491,19:53,27,80,842,906,48.2,19.88,4.476861,1.187,268.612,3.581